### PR TITLE
updating glossary as of July 24, 2023

### LINKED ISSUE #52: The structure with `content` property isn’t recognized properly by the template
It looks like the build for osgeo.geolexica.org doesn’t recognize definition structure with `content` property. See e.g. https://osgeo.geolexica.org/concepts/84/. Same applies to notes (https://osgeo.geolexica.org/concepts/179/) and probably examples, which also now use the `content` property.

### PR DESCRIPTION
**Pull request by HassanAkbar**
updating glossary as of July 24, 2023

fixes #52

### CODE REVIEW

**Comment by strogonoff** [comment]
@HassanAkbar but the updated submodule `osgeo-glossary` still uses the “content” property, I think? what exactly was the fix?

**Comment by HassanAkbar** [comment]
@strogonoff The old concepts don’t have the `content` property in the `definitions` so that is why I have updated the concepts , to use the updated concepts I have updated the `gemfile` to use the latest gem, which I missed earlier.

**Review by ribose-jeffreylau — APPROVED** [review]
👍

**Comment by strogonoff** [comment]
Merged & monitoring site for updates.

**Comment by strogonoff** [comment]
Works!

**Pull request merged**
